version: '3'

services:
  user_db:
    image: postgres
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userservice
    ports:
      - "5433:5432"
    volumes:
      - userservice-db:/var/lib/postgresql
    networks:
      my_network:


  user_service:
    build:
      context: ./UserService
      dockerfile: ./Dockerfile
    container_name: user_service
    ports:
      - "8091:8081"
    environment:
      - DB_IP=user_db
      - DB_PORT=5432
      - DB_DBNAME=userservice
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_network:


  device_db:
    image: postgres
    container_name: device_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: deviceservice
    ports:
      - "5434:5432"
    volumes:
      - deviceservice-db:/var/lib/postgresql
    networks:
      my_network:


  device_service:
    build:
      context: ./DeviceService
      dockerfile: ./Dockerfile
    container_name: device_service
    ports:
      - "8092:8082"
    environment:
      - DB_IP=device_db
      - DB_PORT=5432
      - DB_DBNAME=deviceservice
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_network:

  authentication_db:
    image: postgres
    container_name: authentication_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authenticationservice
    ports:
      - "5435:5432"
    volumes:
      - authenticationservice-db:/var/lib/postgresql
    networks:
      my_network:


  authentication_service:
    build:
      context: ./AuthenticationService
      dockerfile: ./Dockerfile
    container_name: authentication_service
    ports:
      - "8093:8083"
    environment:
      - DB_IP=authentication_db
      - DB_PORT=5432
      - DB_DBNAME=authenticationservice
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_network:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "81:80" 
      - "8081:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
    develop:
      watch:
       - path: ./dynamic                   # watch the whole folder
         action: restart
    networks:
      my_network:


volumes:
  userservice-db:
  deviceservice-db:
  authenticationservice-db:


networks:
  my_network:
    external: true
